### ISSUE TITLE
[文档优化建议] 可以加个codesandbox示例链接吗

### ISSUE THREAD

**Issue by fantasticsoul** [cxy2019731/cxy-react-i18n#1]
可以加个codesandbox示例链接吗，让使用者快速了解运行情况

**Comment by cxy2019731** [comment]
好的！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cxy2019731/cxy-react-i18n"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 上午10:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[cxy2019731/cxy-react-i18n] [文档优化建议] 可以加个codesandbox示例链接吗 (#1)





 
可以加个codesandbox示例链接吗，让使用者快速了解运行情况

**Comment by fantasticsoul** [comment]
嗯嗯，我是concent作者，看到你这个项目发现你这个思路真的挺棒的，等你发出codesandbox链接后我去试试，可能会存在一个问题：
因为你的模块内部调用了run接口，而run接口只能被调用一次，所以对于一个已经使用了concent的项目来说，它那里又调用了一次run，会导致报错。

所以我可能需要对run接口提供一个可选参数 append: boolean, 表示当前run函数是否以append模式来启动，默认是false，当设置为true后，后续的run接口不会报错，因为第一个run设置了append:为true，那后续的run知道了前面的run是用追加模块的方式在运行，这样的话多个第三方模块都可以安全的调用run了。

所以我验证完可以复现这个错误后，后面你的模块需要升级下
```ts
run(yourModels, { append: true  })
```

**Comment by cxy2019731** [comment]
嗯嗯，魂大明白我就在你的群里，昨天刚放上去，当时也有考虑过重复调用的问题，不过都和其他优化问题放到一起去了暂时还没处理0.00.0.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 中午11:21
收件人: ***@***.***&gt;; 
抄送: "从¤来一 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cxy2019731/cxy-react-i18n] [文档优化建议] 可以加个codesandbox示例链接吗 (#1)





 
嗯嗯，我是concent作者，看到你这个项目发现你这个思路真的挺棒的，等你发出codesandbox链接后我去试试，可能会存在一个问题：
 因为你的模块内部调用了run接口，而run接口只能被调用一次，所以对于一个已经使用了concent的项目来说，它那里又调用了一次run，会导致报错。
 
所以我可能需要对run接口提供一个可选参数 append: boolean, 表示当前run函数是否以append模式来启动，默认是false，当设置为true后，后续的run接口不会报错，因为第一个run设置了append:为true，那后续的run知道了前面的run是用追加模块的方式在运行，这样的话多个第三方模块都可以安全的调用run了。
 
所以我验证完可以复现这个错误后，后面你的模块需要升级下
 run(yourModels, { append: true  })

**Comment by fantasticsoul** [comment]
你在群里的id是多少啊，我们群里沟通更方便哈
